version: '3.8'

services:
  backend:
    command: npm run dev
    container_name: todo-backend
    depends_on:
      - postgres
    # Overwrite POSTGRES_HOST in .env file
    environment:
      POSTGRES_HOST: postgres
    env_file: .env
    image: mikaalaoutinen/todo-backend:latest
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app

  postgres:
    image: postgres
    container_name: postgres-todoapp
    env_file: .env
    expose:
      - 5432
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - ./data:/docker-entrypoint-initdb.d
