version: '3.8'

# Add compose file for local development purposes
services:
  backend:
    image: mikaalaoutinen/todo-backend:latest
    container_name: todo-backend
    depends_on:
      - postgres
    environment:
      PORT: 8080
      POSTGRES_HOST: postgres
      POSTGRES_DATABASE: todoapp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 8080:8080
    restart: unless-stopped

  postgres:
    image: postgres
    container_name: postgres_todoapp
    environment:
      POSTGRES_DATABASE: todoapp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    expose:
      - 5432
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - ./data:/docker-entrypoint-initdb.d
