apiVersion: v1
kind: Service

metadata:
  name: postgres-svc
  namespace: main
  labels:
    app: postgres

spec:
  ports:
  - name: db-port
    port: 5432
  # clusterIP: None denotes a "headless service"
  clusterIP: None
  selector:
    app: postgres