apiVersion: v1
kind: ConfigMap

metadata:
  name: todo-broadcaster-configmap
  namespace: todo
  labels:
    app: todo-broadcaster

data:
  CHAT_SERVICE_URL: http://echo-service-svc:8000/echo
  NATS_URL: nats://nats:4222
  