apiVersion: apps/v1
kind: Deployment

metadata:
  name: todo-broadcaster-dep
  namespace: todo

spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-broadcaster
  template:
    metadata:
      labels:
        app: todo-broadcaster
    spec:
      containers:
        - name: broadcaster
          image: mikaalaoutinen/todo-broadcaster
          envFrom:
            - configMapRef:
                name: todo-broadcaster-configmap
