apiVersion: v1
kind: ConfigMap

metadata:
  name: postgres-configmap
  namespace: main
  labels:
    app: postgres

data:
  POSTGRES_DATABASE: pingpong
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
  PGDATA: /var/lib/postgresql/data/pgdata
