apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-credentials
  namespace: main
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCjNWrnyqZzecMtKsegPCmeeADn8jjxLAnPyWL/eZzpanLtx0cqeIXOa+/0HTSx3xR7jOfw75rAgPH1kfSMJW1aLaijVrYhr0edPtPjqeRF3lXtPTWFfV5MTNxpS6eGFR+RZLNm2xFMvZtgzGKZiK1aQ5gB0TmpE5TrPt4KzYB1cU97PfvojoHLidOQavVJeNXO0922NYCVaHs/PKHr0cC/Ej15YsC0ObcW6Mct1AhWFkGpZdJVp7v0akiJKFdnNxkv4wJ/yym1dDZlEC1vw+LYdk/k2E8Jc4lheF6CGEM+787aaJtSQCu3lGy3Nu32ADb/DwyEjvdavktyo1cHuAOVXC9f7JAP+yBuP1uJHRaAjJMKfD4HeJxc7fRYxmFUPuOgJXB0lGiCjb1OzSQ5XQ7zTIhQEesHYbm+qouqT9PjTZIV0Zb2gc2mHoXIi+GBENHVVHvjN+i124DEpvZ3WoAZwaE7udarYDfG3REryBrUlVaOZqMJBnTDsLkT7sZVgt6is8r9boSVmU+9Nij2DQoRClOtSk3Wxq477KzHHEpqSHKa4ADT6op4fTceERQjSXKU93E6n+p3ixrzfwkJOVD3tFgQC+z6UPWKEb/rceFOGtlohxEWc62vqTrQQmdMMDoVRONKYqJrdqQC3bwPO0hjJ8VJUb6N4BmOE7sY+eayrIrS3YrmsBzFrasy8ouQOUI7IhLONw==
    POSTGRES_USER: AgCwagXXmV1TzMqvfG0FPsQPO1up1F/zq0r10L1LNKPXqmHuvklFun/LDXZnKnU8BSi431bOtuR+XsWb7jw+KLYnoSbQr2HFYiIpQFDsGvjWqighS+eR+mixYXq6FnjZHoZvXSe0aew2EdjlqBCWCcgDV0u9hLKEJGmYllHalzH/baxnFkxP4N6XM+QrLsCeS3cSY9Ybwej+gtWhcCWRhUiVOGYjEnqnQcHs0LgGR1+HEIpvEbC8DMSeJFMcMJiAKDPolPXKj4vQkmKtkkFvyyau/OgHjcF0ePcf3N+s+Naj++8HW/zo7W4g/lgRI1dN26HdB/7cpPYj7B2jkXiBWwxUPPbkQbp3kfNgh7hP4vGKm3Oba6/q81MWR6G6samlgshMOvESe5tlVR+niU0Nvzmhk7DS0SQ4roJIIpSTqTBkWj6BIi70Y9bVi6JRepwq4m6Nm59Ccbct3QA4E8EF/tzZeR1n2X1cZCUn3rpy/p1r2yZgsnsC7G9o1cKomkckvfyz1zlwZC1WRNkjXiDwlqbgVZOAklOvUswH/FcEEFkT6ImmtnDiNKkkFoZ38xRyT6qUa4iFgg1YxdIruGRjJiYi/i+SVrQi4tAw6IrI8NVltNMLZf1uRXC8mfwlaGpvWKMzz7QvdnQLUWr+sdveSdaC5vDjoRD8gD7GDeQ+2UU40qpUL8EJ6ukUDr5iku1dPOcbvYAudA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-credentials
      namespace: main

