apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: postgres-statefulset
  namespace: main
  labels:
    app: postgres

spec:
  serviceName: postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        envFrom:
          - configMapRef:
              name: postgres-configmap
        ports:
        - name: db-port
          containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: postgres-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-initdb
          configMap:
            name: postgres-initdb
  
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
        namespace: main
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi
