apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate

metadata:
  name: restart-rate
  namespace: todo

spec:
  metrics:
  - name: restart-rate
    initialDelay: 2m
    successCondition: result < 0.01
    provider:
      prometheus:
        address: http://prometheus-stack-kube-prom-prometheus.prometheus:9090
        query: |
          scalar(
            sum (rate (container_cpu_usage_seconds_total{namespace="todo"}[1m])) / sum (machine_cpu_cores) * 100 -
            sum (rate (container_cpu_usage_seconds_total{namespace="todo"}[1m])) / sum (machine_cpu_cores) * 100 offset 2m)
          )
