apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-credentials
  namespace: todo
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBgIYbIMmagYtHzdoezuHqO2QCnWDTzsmO3HSjyM63SQfSd/kRjeLIJcLum0K8ehID0E9QLZZZzC9I3+R/UHovhu1ae0cQoSHwSSOyll0Y7CYBS2wbtAgEnsq6Ppm16Rcl3R3I6xCj7EGc9Vr0msuBOhYIgeRWH4elnO3nsTEjG6pJ8itSyEXzPt1z3aW1niaDPbB1GZyer1yZt110MNT+7rlRj2gqaeIi0epPRh5Mk6D3ZCC1GPjVb93RgRFI9b6T8TZiEDMD1nnr2Jdu1Loq/azaAqBokY+zjs0GJYdtV4TJT7OOv1qCzy5qXFgRhJ/LKphQ1/ZCYoZEa6TXk/KFk+ESlAx6M8BZ/dyx+cXBFtIflMvUZDxPDZQOibrRQGRx+rXSefdPt5+2DeIMcxpZwLSItWsWphzblB18DUWNO2N3Ab0DOZQewLv9eyBOaINJCP118p0r3zOuazyQGs+gaXMAoLohXb7Soqkzjr1OPNkdV2K/7pU31GHFpw/SP60L9I3fXbUE1RNcVp9CsFSnN6YIDZvI6JRcvj8auDKQPS5a21OYEEgIL7XssAVp763YWHNRcn19LmQL9MZF9Dgv4g0EGuO2H255vDak1czG+ZbYW2bKrvNOEcx4tN+FflmRaZqyybdmwaeGk8+X64SGLgBDSXxtZUzC04rTlPj4wBI9c8bMJxSTKSZiEMjB2e3Vg06j/+A==
    POSTGRES_USER: AgBSqpMqnpLyKgq7HJ3AQ8EfmNq4Fu1LUktj31tUO+pkmAHyuO7GlHd3tN2ggczQ/gtaBVNXgqxrPyfrlC8rjKF6qAOUBgsQx7iRbc4AtnDVpblr+6mMuu1M+jXT10OHEIi1B24HldtdYtyBJJSXI/ULtbz7apQysS1QA3vyKQVrRNjSpsHiB/gmE7VY4xcjaffYKTUiHhc0cEsFpuPHCy61y4xBLpF3WUTtqe2MuXPE56LM+iga3oc4YWHbMtk8HgmxOdem7lboKAIgC4fqbWMMbrcqnyFPgTa1/L1Q26WjQD9W1UbYp05mZ/JG5E+m+0B+G7tLxlSZqUWRmWzGuGLZH5x/pJS4tBeRU0FIwlGhDPiayIyAfOR33/0O1ULJdV+nwUUT7jxXCmE7wNLR65aWIOgwC/KOHvjCRLNY5ovG0ZGFONfiNUCpSSOed0a5eACmfjEVtW3upPYJCsT5hz2xfGsSEtQsIPY09K3XCu260txTn13OVX4u5/5EM700kQmJnJskSaiyLNmZOsSZRAy54eKnOcaAUJoB15LyBAjelm41YzkKXpD9tyHAYohjjByihZjdzmPDk9m0yF391lY9tMgmdpXQ7Ps+zHkTTB83yNCAOtV0iGU9QBiM0/Mnuhe2aW2hTBaOq/YtByqHeEVy8yL9vN8np0tzw7HDhIsMnOM79CtTV7IcgbR1Wtc1pfGqB0+8Dg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-credentials
      namespace: todo

