apiVersion: v1
kind: Service

metadata:
  name: postgres-svc
  namespace: todo
  labels:
    app: postgres

spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
  - name: db-port
    port: 5432
    targetPort: 5432
