apiVersion: v1
kind: ConfigMap
metadata:
  name: main-app-reader-configmap
  namespace: main
data:
  MESSAGE: Hello
  PORT: '8080'
  PINGPONG_READINESS_CHECK: http://pingpong-svc/monitoring/readiness
  PINGPONG_URL: http://pingpong-svc/pingpong
