version: '3.8'

# Add compose file for local development purposes
services:
  postgres:
    image: postgres
    container_name: postgres_pingpong
    environment:
      POSTGRES_DATABASE: pingpong
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - ./data:/docker-entrypoint-initdb.d
