apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
  namespace: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: mikaalaoutinen/todo-backend:latest
          envFrom:
            - configMapRef:
                name: todo-backend-configmap
            - secretRef:
                name: postgres-credentials
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /api/monitoring/readiness
              port: 8080
