apiVersion: apps/v1
kind: Deployment

metadata:
  name: echo-service-dep
  namespace: todo

spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-service
  template:
    metadata:
      labels:
        app: echo-service
    spec:
      containers:
      - name: echo-service
        image: mikaalaoutinen/echo-service
        ports:
        - name: tcp
          containerPort: 8000
