apiVersion: v1
kind: Service

metadata:
  name: echo-service-svc
  namespace: todo
  labels:
    app: echo-service

spec:
  clusterIP: None
  selector:
    app: echo-service
  ports:
  - name: tcp
    port: 8000
    targetPort: 8000
